// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskcegTCE8ALfoNm8eWsN3MwNPRTfNpFA',
    appId: '1:775312399615:web:5de8e56e631af89fe380ca',
    messagingSenderId: '775312399615',
    projectId: 'sparkle-code',
    authDomain: 'sparkle-code.firebaseapp.com',
    storageBucket: 'sparkle-code.firebasestorage.app',
    measurementId: 'G-HR4RH7R353',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh65Mv5dW6TbzzdG_1Lo4fXu1yUAHMpfw',
    appId: '1:775312399615:android:c7cc63bb71de7518e380ca',
    messagingSenderId: '775312399615',
    projectId: 'sparkle-code',
    storageBucket: 'sparkle-code.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI47-B3g1yLfE7ubsqXVMAXoD6svzenkE',
    appId: '1:775312399615:ios:f257897ae745ce77e380ca',
    messagingSenderId: '775312399615',
    projectId: 'sparkle-code',
    storageBucket: 'sparkle-code.firebasestorage.app',
    iosBundleId: 'dvlpr.com.sparkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI47-B3g1yLfE7ubsqXVMAXoD6svzenkE',
    appId: '1:775312399615:ios:f257897ae745ce77e380ca',
    messagingSenderId: '775312399615',
    projectId: 'sparkle-code',
    storageBucket: 'sparkle-code.firebasestorage.app',
    iosBundleId: 'dvlpr.com.sparkle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAskcegTCE8ALfoNm8eWsN3MwNPRTfNpFA',
    appId: '1:775312399615:web:0041cdf4b9f1e55de380ca',
    messagingSenderId: '775312399615',
    projectId: 'sparkle-code',
    authDomain: 'sparkle-code.firebaseapp.com',
    storageBucket: 'sparkle-code.firebasestorage.app',
    measurementId: 'G-KWCT1W6R26',
  );

}